server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/invoiceDB
spring.application.name=invoice-backend

# Gmail SMTP Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anhtuan11.cwt@gmail.com
spring.mail.password=ckvurpchyihssalt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.from=anhtuan11.cwt@gmail.com
